#!/bin/bash

MYSQL_USER='root' 
MYSQL_PASSWORD='!Ahhjntf0p02u1'

read -p "Enter MASTER_LOG_FILE=" MASTER_LOG_FILE
read -p "Enter MASTER_LOG_POS=" MASTER_LOG_POS

echo "STOP SLAVE; CHANGE MASTER TO MASTER_HOST='192.168.1.36', MASTER_USER='root', MASTER_PASSWORD='!Ahhjntf0p02u1', MASTER_LOG_FILE='$MASTER_LOG_FILE', MASTER_LOG_POS=$MASTER_LOG_POS, GET_MASTER_PUBLIC_KEY = 1; START SLAVE; show slave status\G" | mysql -uroot -p$MYSQL_PASSWORD



